name: Broken Build
on: [push]

jobs:
  test-fail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run broken python script
        # This is missing a closing parenthesis ')' so it will CRASH
        run: python -c "print('Hello PatchFlow'"